export type PlanetId = 'identidade' | 'trajetoria' | 'jornadas' | 'sistemas' | 'mentoria' | 'conexao';
export interface Planet { id: PlanetId; name: string; description: string; region: string; color: string; x: number; y: number; size: number; stations: string[]; kicker: string; headline: string; }
export const planets: Planet[] = [
  { id: 'identidade', name: 'Identidade', description: 'O que me move', region: 'ORIGEM', color: '#9bdcc4', x: 24, y: 40, size: 114, stations: ['Posto de comando', 'Minha abordagem', 'Formação & idiomas'], kicker: 'ESTRATÉGIA ENCONTRA EXECUÇÃO', headline: 'Conectar é o meu ponto de partida.' },
  { id: 'trajetoria', name: 'Trajetória', description: 'Caminhos e evolução', region: 'ORIGEM', color: '#d5b489', x: 54, y: 19, size: 66, stations: ['Liderança & Martech', 'Campanhas & CRM', 'Primeiros passos'], kicker: 'UMA CARREIRA EM MOVIMENTO', headline: 'Cada etapa ampliou o horizonte.' },
  { id: 'jornadas', name: 'Jornadas', description: 'Projetos com impacto', region: 'OPERAÇÕES', color: '#b8a0df', x: 70, y: 57, size: 95, stations: ['Case Worten', 'Missão de CRM'], kicker: 'DA IDEIA AO RESULTADO', headline: 'Boas jornadas começam com boas conexões.' },
  { id: 'sistemas', name: 'Sistemas', description: 'Meu universo técnico', region: 'OPERAÇÕES', color: '#87b7db', x: 40, y: 78, size: 73, stations: ['Ecossistema Salesforce', 'Código & dados', 'Certificações'], kicker: 'TECNOLOGIA COM PROPÓSITO', headline: 'A ferramenta certa. Para o desafio certo.' },
  { id: 'mentoria', name: 'Mentoria', description: 'Crescer, compartilhar', region: 'CONEXÕES', color: '#dfac88', x: 86, y: 27, size: 49, stations: ['Orientação voluntária', 'Treinamento de equipes', 'Primeiro contato'], kicker: 'CONHECIMENTO EM CIRCULAÇÃO', headline: 'O próximo passo fica melhor acompanhado.' },
  { id: 'conexao', name: 'Conexão', description: 'Vamos conversar', region: 'CONEXÕES', color: '#acd3ce', x: 89, y: 83, size: 43, stations: ['Abrir um canal', 'LinkedIn', 'Levar o currículo'], kicker: 'TRANSMISSOR DISPONÍVEL', headline: 'Uma boa conversa pode abrir novos caminhos.' },
];
